name: orbita
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_generative_ai: ^0.4.4
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  image: ^4.2.0
  fftea: ^1.4.0
  path_drawing: ^1.0.1
  uuid: ^4.4.0
  google_fonts: ^6.2.1
  fast_noise: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
